name: Deploy to GitHub Pages

on:
  push:
    branches: "main" # Если у тебя ветка называется master, замени на "master"

  # Позволяет запускать деплой вручную из вкладки Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ hashFiles('package-lock.json') != '' && 'npm' || hashFiles('bun.lockb') != '' && 'bun' || 'pnpm' }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci;
          elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm i --frozen-lockfile;
          elif [ -f bun.lockb ]; then corepack enable && bun install --frozen-lockfile;
          else npm install;
          fi

      - name: Build
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm build;
          elif [ -f bun.lockb ]; then bun run build;
          else npm run build;
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Папка, куда Vite собирает готовый проект

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
